### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by samajammin** [smartcontracts/eth2-book#17]
Amazing resource! I think it's awesome that [you decided to open-source this](https://twitter.com/kelvinfichter/status/1502337037982216194?s=20&t=s9lYJYtOvnp9GnFJyyhGIg).

One request: please explicitly add license. Note that making the GitHub repo public doesn't automatically make it open source:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by smartcontracts** [comment]
Errr whoops, I forgot to copy the license over. Will do first thing tomorrow (should be MIT).

**Comment by smartcontracts** [comment]
Added the license. I ported the project over from Gatsby to Vuepress and forgot to copy the license over. Thank you!

**Comment by smartcontracts** [comment]
Shoot me an ETH address and I'll send you an NFT for pointing this out :-)
