### ISSUE TITLE
Tech stack used for the website/book?

### ISSUE THREAD

**Issue by shafu0x** [smartcontracts/eth2-book#20]
Hey,

which frameworks are used to produce the website, book etc?
I looked around the repo and book but could not find any info about it.

Amazing project btw...

**Comment by shafu0x** [comment]
I guess it is Vuepress?

**Comment by smartcontracts** [comment]
Yes it's Vuepress. I should probably point that out in the contributing guide. Vuepress is nice since it's very straightforward and easy to customize.
