### ISSUE TITLE
latex rendering issue 

### ISSUE THREAD

**Issue by xremora** [smartcontracts/eth2-book#4]
looks the maths equations are not rendered

**Comment by smartcontracts** [comment]
Ah yeah you're right. I recently moved the book from gatsby to vuepress, probably related to the move.

**Comment by smartcontracts** [comment]
Fixed by updating to a better latex plugin. Should look correct now!

**Comment by smartcontracts** [comment]
Thanks for creating this issue, please feel free to send me an ETH address and I'll make you an NFT :-)
